### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by TobiasFaller** [andportnoy/riscv-disassembler#1]
Hey,

I like your implementation of the RISC-V disassembler and would like to use it in a project.
Unfortunately, there is no license included in the repository.
Would it be possible for you to add one?

Best Regards,
Tobias Faller

**Comment by vazhnov** [comment]
Hello!

I found link to this project from https://olimex.wordpress.com/2021/02/23/hello-risc-v-we-got-samples-of-the-new-esp32-c3-module-and-it-is-only-13x17-mm/

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by enthusi** [comment]
Hi, I join the group of interest in a license since I would love to use it for a small bare-metal project.
Nice work!

**Comment by andportnoy** [comment]
@TobiasFaller @vazhnov @enthusi Hi all, my apologies for the silence, I had not been receiving my GitHub notifications. Please let me know if you are still interested and what type of license would suit your use case.

**Comment by andportnoy** [comment]
@TobiasFaller @vazhnov @enthusi I added MIT.

**Comment by vazhnov** [comment]
@andportnoy , thank you very much!

**Comment by enthusi** [comment]
Thank you. Wonderful.

**Comment by TobiasFaller** [comment]
Hello @andportnoy, thank you very much! I can't wait to use it in my project.
